### ISSUE TITLE
Docker tests do not work out-of-the box

### ISSUE THREAD

**Issue by techhazard** [testxio/testx-quickstart#1]
When I try to run the docker tests with `npm test` I get the following error:

```sh
$ npm run test

> testx-quickstart@4.0.0 test /home/techhazard/crawler
> docker run --rm -it -u `id -u`:`id -g` -v `pwd`:/work --net=host testx/protractor conf.coffee

groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
sudo: unknown user: protractor
sudo: unable to initialize policy plugin
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testx-quickstart@4.0.0 test: `docker run --rm -it -u `id -u`:`id -g` -v `pwd`:/work --net=host testx/protractor conf.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testx-quickstart@4.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/techhazard/.npm/_logs/2018-06-26T12_37_11_048Z-debug.log
```

The complete log mentioned above contains:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle testx-quickstart@4.0.0~pretest: testx-quickstart@4.0.0
6 info lifecycle testx-quickstart@4.0.0~test: testx-quickstart@4.0.0
7 verbose lifecycle testx-quickstart@4.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle testx-quickstart@4.0.0~test: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/techhazard/crawler/node_modules/.bin:/home/techhazard/bin:/home/techhazard/install/bin:/home/techhazard/.local/bin:/home/techhazard/.cargo/bin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/techhazard/.fzf/bin
9 verbose lifecycle testx-quickstart@4.0.0~test: CWD: /home/techhazard/crawler
10 silly lifecycle testx-quickstart@4.0.0~test: Args: [ '-c',
10 silly lifecycle   'docker run --rm -it -u `id -u`:`id -g` -v `pwd`:/work --net=host testx/protractor conf.coffee' ]
11 silly lifecycle testx-quickstart@4.0.0~test: Returned: code: 1  signal: null
12 info lifecycle testx-quickstart@4.0.0~test: Failed to exec test script
13 verbose stack Error: testx-quickstart@4.0.0 test: `docker run --rm -it -u `id -u`:`id -g` -v `pwd`:/work --net=host testx/protractor conf.coffee`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid testx-quickstart@4.0.0
15 verbose cwd /home/techhazard/crawler
16 verbose Linux 4.15.0-23-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
18 verbose node v10.5.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error testx-quickstart@4.0.0 test: `docker run --rm -it -u `id -u`:`id -g` -v `pwd`:/work --net=host testx/protractor conf.coffee`
22 error Exit status 1
23 error Failed at the testx-quickstart@4.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Is there something I'm missing? I can run other docker containers just fine (e.g. hello-world).

`npm run test-local` works fine as well

**Comment by greyarch** [comment]
Hi Vince,
The problem seems to be in your attempt to provide a particular user and group when running the container. If you remove the `-u...` part it will work, maybe it is enough for you? It is possible that you get a **testresults** folder with unwanted ownership (root), however, hence the `-u` bit that tries to rectify this, right?
Anyway, the **testx/protractor** image is rather old and this error is not something I wanna tackle :)
My recommendation is you use the much newer **testx/chrome** image, that relies on the relatively recent headless mode of chrome. To do this you need to change your execution a bit:
- change the chrome args in the conf.coffee to something like
```
    chromeOptions:
      args: ['--no-sandbox', "--headless", "--disable-gpu", "--window-size=1024,800"]
```
- make protractor a local dependency `npm i -D protractor`
- change the scripts in your package.json to include
```
...
  "scripts": {
    "pretest": "webdriver-manager update",
    "test": "protractor conf.coffee"
   }
...
``` 
- run the tests with
```
docker run -it --rm -v $(pwd):/work -u $(id -u):$(id -g) testx/chrome
```

I like this approach much better because you do not rely on a virtual frame buffer to run a "real" browser. This is why Chrome finally has a headless mode, after all. As a bonus, you have much tighter control over the protractor version you are using.

Hope all of this helps :)

**Comment by techhazard** [comment]
This works :+1: 

Thank you for the help :smile: 

The `testx/chrome` test now uses the same browser as the `test-local` test uses, right? (except for the headless part)

**Comment by greyarch** [comment]
Well, I do not know what test-local uses, that's the (Chrome) browser installed on your system. You do not need test-local anymore, running `npm test` now does the same.
**testx/chrome** is a simple Docker image with NodeJS and Chrome in it. 
It is suitable for headless execution only - there is no display in the container.

**Comment by techhazard** [comment]
Okay thanks for the "heads" up :-P
